debouncing of daily production
SonnenladenGmbH/APsystems-EZ1-API pull request #31
Opened 2024-08-21 19:23 UTC by patman15

Hey @mawoka-myblock,

here is my proposal (attempt #4) to fix the restart of the daily production (fixes issue #30).
Ready to receive feedback, I ran your tests, pass, I tested locally if functionality works, works, I can add unit tests if the principle setup is ok for you.

Best regards,
Patrick

2024-08-21 19:28 UTC, mawoka-myblock requested changes
Awesome, thanks! The cherry on to would be tests! Unit tests of `_debounce()` are/would be enough

2024-08-21 19:28 UTC, mawoka-myblock commented on APsystemsEZ1/__init__.py
> +    class DebounceVal:
```suggestion
    class _DebounceVal:
```

To make it "private"

2024-08-21 19:28 UTC, mawoka-myblock commented on APsystemsEZ1/__init__.py
> +        self._e2 = self.DebounceVal()
```suggestion
        self._e1 = self._DebounceVal()
        self._e2 = self._DebounceVal()
```

2024-08-21 19:28 UTC, mawoka-myblock commented on APsystemsEZ1/__init__.py
> +        debounce_values: bool = False,
```suggestion
        enable_debounce: bool = False,
```

2024-08-21 19:28 UTC, mawoka-myblock commented on APsystemsEZ1/__init__.py
> +        self.debounce_values = debounce_values
```suggestion
        self.enable_debounce = enable_debounce
```

2024-08-21 19:28 UTC, mawoka-myblock commented on APsystemsEZ1/__init__.py
> +    def _debounce(self, state: DebounceVal, new_state: float) -> float:
```suggestion
    def _debounce(self, state: _DebounceVal, new_state: float) -> float:
```

2024-08-23 13:30 UTC, mawoka-myblock commented
The merge will take some time as I won't merge without tests, but I'll do them eventually if you don't feel like that. But so far, it looks good!

2024-08-23 14:01 UTC, patman15 commented
Hey!

I'm almost done with tests, just fighting with getting the datetime mocked.
Give me a few hours/days. 
--
Touched, not typed.

2024-08-23 14:03 UTC, mawoka-myblock commented
That's soo awesome! Thank you and take your time. We're not in a rush

2024-08-24 15:49 UTC, patman15 commented
Please check my PR including the unit tests. Happy to receive feedback! Thanks!

2024-08-24 17:17 UTC, patman15 commented
Just thought again about the PR, will improve the tests a bit further.
--
Touched, not typed.
https://threema.id/ABSJVUAW

2024-08-24 19:05 UTC, patman15 commented
So, now I'm happy, hope you are satisfied as well!

2024-08-25 17:16 UTC, mawoka-myblock commented
Thank you! I'll check the PR soon!

2024-09-16 11:27 UTC, mawoka-myblock commented
Oh god, already 3 weeks?! Huge apologies so far! Completely forgot this PR!

2024-09-16 14:24 UTC, patman15 commented
All good, I'm patient as long as you won't make me redo it a forth(?) time. ;-) Hope you don't do big changes on the main!

2024-09-16 14:48 UTC, mawoka-myblock approved these changes

2024-10-05 15:50 UTC, mawoka-myblock commented
Man, I again forgot you! I'm really sorry for the delays here, but y'know, there are other projects. Just some and this right here unfortunately has a low(ish) priority! Sorry for that

2024-10-18 09:49 UTC, merged

2024-10-18 09:49 UTC, mawoka-myblock commented
Finally! Thank you soo much for your patience and your work!

2024-10-18 10:01 UTC, patman15 commented
Thank you for all the work! I will soon bug you with a PR for the HA integration, to enable the behaviour there. :wink:

2024-10-18 10:22 UTC, mawoka-myblock commented
> Thank you for all the work! I will soon bug you with a PR for the HA integration, to enable the behavior there. 😉

Just wanted to say that. I'll release a new version of this API now so you can start immediately if you want

2024-10-18 11:11 UTC, patman15 commented
Currently I can't work on it. I plan to continue at the end of this month.
Do you want me to make the new behaviour, which I think is quite transparent, optional or can I enable it by default in HA? Just to check before I start. :-)

2024-10-18 11:13 UTC, mawoka-myblock commented
I think that you can enable it by default