Add unit tests
SonnenladenGmbH/APsystems-EZ1-API pull request #7
Opened 2023-12-13 09:40 UTC by CM000n

Proposal for adding unit tests

2023-12-13 09:47 UTC, mawoka-myblock commented
Why did you close this PR? Because there's no way to have a reliable Inverter available, right?

2023-12-13 11:24 UTC, CM000n commented
> Why did you close this PR? Because there's no way to have a reliable Inverter available, right?

No, I have closed it for the time being because it looks a bit confusing, as all the changes from the refactoring PR are also displayed.
I will open it again when the refactoring PR has been merged.

2023-12-13 11:26 UTC, mawoka-myblock commented
Sure!

2023-12-14 14:21 UTC, mawoka-myblock requested changes
Every "raw" response from the inverter is built like the following:
```json
{
	"data": "DATA",
	"status": 0
}
```

If you want, you can add this, since I've never experienced this status being different from `0`.

2023-12-14 16:12 UTC, CM000n commented on .github/workflows/testing.yml
> +        run: "poetry install"
A `poetry install` will install everything.
You can exclude dev dependencies explicitly with the cli arg `--without dev`

2023-12-14 16:15 UTC, CM000n commented
> Every "raw" response from the inverter is built like the following:
> 
> ```json
> {
> 	"data": "DATA",
> 	"status": 0
> }
> ```
> 
> If you want, you can add this, since I've never experienced this status being different from `0`.

Hello, please comment on explicit code line numbers. Such a detached comment makes it somewhat difficult to understand exactly what you mean and where.

2024-01-01 15:06 UTC, merged

2024-01-01 15:06 UTC, mawoka-myblock commented
Thanks man! I thought I'd fix these small thinks myself to not annoy you even further! Thank you so much for your work and welcome to 2024 ;) ❤️